### PR TITLE
Constant single individual

### PR DESCRIPTION
**Pull request by Tess-LaCoil**
Added stan file, data template, and data template testing for the constant model with a single individual. Also tidied up some of the code and comments so that the single and multiple individuals for the constant model would be more clearly matched.

### CODE REVIEW

**Review by dfalster — CHANGES_REQUESTED** [review]
Nice work. 

You need to add tests checking that models run !

Also good to add tests checking that they fail when you add the wrong inputs

**Comment by Tess-LaCoil** [comment]
> Nice work.
> 
> You need to add tests checking that models run !
> 
> Also good to add tests checking that they fail when you add the wrong inputs

Okay, I'll need to do those for the multiple individuals as well then. I thought we were going to do them as a collection once Fonti was back. Happy to set up stuff and wait for then. Is it possible to have multiple concurrent branches each one implementing a different model or should they be done one at a time?

**Comment by dfalster** [comment]
I didn't know you already had a plan. 

Generally I suggest adding tests at the time.

**Comment by dfalster** [comment]
For inspiration, take a look at sizedist package

https://github.com/traitecoevo/sizedist/tree/master/tests/testthat

**Comment by fontikar** [comment]
Let's close this PR to avoid confusion, as we have established a new workflow on the `constant` branch. Closing will not delete the `constant_single_individual` branch

**Pull request closed without merging**
