### PR TITLE
Added linear DE

### PR DESCRIPTION
**Pull request by Tess-LaCoil**
Removed old linear regression code.

Added linear DE model with different parameterisation and wider priors than vB model for easier investigation of pathological parameter stuff.

### CODE REVIEW

**Comment by Tess-LaCoil** [comment]
Dan, this is failing because of a file I can't find in the repo: rmot-Ex.R Is this some automatically generated file?
I've removed the linear regression model because it's outdated code and not used, also I want the name 'linear' for a linear DE.

**Comment by dfalster** [comment]
Hi Tess, that file is generated during the package testing, it contains all the examples listed in your function documentation. 

In this case, we can see it failing here, so where is that in the examples?

https://github.com/traitecoevo/rmot/actions/runs/10121851792/job/27993265184?pr=26#step:6:152

I'd suggest

1. Test locally by running `rcmdcheck::rcmdcheck()`. should fail, mirroring the fail in online testing

2. delete everything in folder `man` and then rerun `devtools::document()`

3. retest locally by running `rcmdcheck::rcmdcheck()`

**Comment by Tess-LaCoil** [comment]
Found the old linear reg stuff in the R files for the rmot_assign_data and rmot_models as examples. I've removed it from those. Once this is sorted and the associated tidying up done I'll start on re-doing the documentation.

**Comment by Tess-LaCoil** [comment]
I discovered that warnings get thrown if there is undocumented stuff so I had to re-insert that. Ready to go now.

**Review by dfalster — APPROVED** [review]

**Pull request merged**
